name: Release Package

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install
      - run: |
          npx puppeteer browsers install chrome
      - name: Run test
        run: |
          for i in {1..3}; do
            echo "Attempt $i"
            if pnpm test:google; then
              echo "Success on attempt $i"
              exit 0
            fi
            echo "Attempt $i failed, retrying..."
          done
          echo "All attempts failed"
          exit 1
  publish:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
